# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_picture', models.FileField(upload_to=b'')),
                ('user_banner_picture', models.FileField(upload_to=b'')),
                ('mobile_phone', models.TextField()),
                ('is_verified', models.BooleanField(verbose_name=False)),
                ('birthday', models.DateField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('gender', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
