# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeShareIo', '0003_auto_20161127_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=1000),
        ),
    ]
