# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeShareIo', '0004_auto_20161130_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_banner_picture',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_profile_picture',
            field=models.FileField(upload_to=b''),
        ),
    ]
