# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeShareIo', '0005_auto_20161201_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_banner_picture',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_profile_picture',
            field=models.CharField(max_length=1000),
        ),
    ]
