# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeShareIo', '0006_auto_20161201_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_banner_picture',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_profile_picture',
            field=models.FileField(upload_to=b''),
        ),
    ]
